---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
    - wget

install:
  # Install ansible and ansible-lint
  - pip install ansible
  - pip install ansible-lint

  # Check ansible version
  - ansible --version

  # Install packer
  - wget --secure-protocol=TLSv1_2 https://releases.hashicorp.com/packer/0.12.1/packer_0.12.1_linux_amd64.zip -O packer.zip && unzip packer.zip
  - ./packer --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=ansible/roles' > ansible/ansible.cfg

script:
  # Validate packer template
  - ./packer validate packer-debian9-qemu-kvm.json

  # Syntax check ansible playbook
  - ansible-playbook -vvvv ansible/playbook.yml -i 'localhost,' --syntax-check

  # Lint check ansible playbook
  - ansible-lint ansible/playbook.yml
