---
- name: Install vim-nox
  package:
    name: vim-nox
    state: present
  become: yes

- name: Set default editor to vim-nox
  alternatives:
    name: editor
    path: "/usr/bin/vim.nox"
  become: yes
