---
- name: Configure eth0 in network interfaces
  replace:
    dest: "/etc/network/interfaces"
    regexp: '(?:(?:eno|ens|enp)\w+)'
    replace: 'eth0'
  become: yes

- name: Configure grub to disable persistent network names
  replace:
    dest: "/etc/default/grub"
    regexp: '(^\s*GRUB_CMDLINE_LINUX="\s*.*?)(?:\s*net\.ifnames\=[0-9]\s*)*(.*"*$)'
    replace: '\1net.ifnames=0 \2'
  become: yes
  register: configure_grub_disable_persistent_network_names

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  become: yes

- name: Update grub
  shell: update-grub
  become: yes
  when: configure_grub_disable_persistent_network_names.changed

- name: Change root password
  user:
    name: root
    update_password: always
    password: $6$rounds=656000$R4pKjHiNohgvcawb$r.924Bck3zOCb2jKQSairUblI9cUSlGQcwtepPFrgbLKCcf5YqD5QldZhLYz0x/vqEXNm5nb8u/stGidTpcnz/
  become: yes