---
- hosts: all
  roles:
    - { role: serial-console,
        when: not ec2ami|bool }

  pre_tasks:
    - name: Install misc packages
      package:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - acpi
        - apt-transport-https
        - ca-certificates
        - curl
        - dbus
        - dnsutils
        - gdisk
        - htop
        - iftop
        - iotop
        - lsof
        - netcat-openbsd
        - ntp
        - parted
        - psmisc
        - rsync
        - smartmontools
        - systemd
        - tcpdump
        - vim
        - wget

    - include_tasks: tasks/disable-persistent-network-names.yml
      when: not ec2ami|bool

    - include_tasks: tasks/salt-minion.yaml
      when: not ec2ami|bool
